# Generated by Django 4.1.2 on 2022-10-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='physic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
    ]
